{% set name = "simpful" %}
{% set version = "2.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/simpful-{{ version }}.tar.gz
  sha256: 00a720de3e884491aec9b3e7a8a719660b4e11029ed37093611c66edd1fffe33

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.12.0
    - scipy >=1.0.0
    - requests

test:
  imports:
    - simpful
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aresio/simpful
  summary: A user-friendly Python library for fuzzy logic
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hechth
    - aresio
    - sspola
